### ISSUE TITLE
Use Semantic Versioning so we can keep track of new contents

### ISSUE THREAD

**Issue by stavarengo** [fdv/running-elasticsearch-fun-profit#36]
Great work @fdv
I am almost at the end of the "book".

What do you think of using [https://semver.org/](semantic versions) so we can keep up with your work. Thus readers could ask GitHub to notify when new versions are released.

Being the semantic version made up of at least three numbers (MAJOR.MINOR.PATCH), I thought of something like this:
- MAJOR version when you add a new chapter.
- MINOR version when you significantly change something in a way that those who had read the old content would have to read it again to fully understaind the subject.
- PATCH version when your changes does not affect the understanting of subject. Those who had read it does not need to read it again.

**Comment by fdv** [comment]
Hi,
I love the idea even though I'm not sure how I will manage it since I work on the "book" an iterative way (changing a few things here and there, adding or upgrading content) and have no "releases" yet.

I need to find a way to structure my work so I can do actual releases

**Comment by fdv** [comment]
Done.

**Comment by stavarengo** [comment]
Hi @fdv. I am glad you accepted my suggestion.

> I love the idea even though I'm not sure how I will manage it since I work on the "book" an iterative way (changing a few things here and there, adding or upgrading content) and have no "releases" yet.

I was thinking about what you said, and it seems to me that you will rarely change the PATCH version. This is not a problem, since a change in the PATCH part does not affect your readers' understanding of the subject. So you can always leave the PATCH version as zero, or change it when you feel like, without the pressure of having to release a new version every time you "correct a misspelling", for example.

Since you already have started using semver, I would also suggest that you tell your readers you are following it, by adding a text rigth on the top of you [README.md](https://github.com/fdv/running-elasticsearch-fun-profit/blob/master/README.md) explaing how and when you will change each version number, just like you did in the [description of your first release](https://github.com/fdv/running-elasticsearch-fun-profit/releases/tag/v1.0.0). So everyone will know that you follow this pattern immediately when they arrive in your repository.
