### ISSUE TITLE
what is http nodes？

### ISSUE THREAD

**Issue by mingyitianxia** [fdv/running-elasticsearch-fun-profit#46]
In [https://github.com/fdv/running-elasticsearch-fun-profit/blob/master/004-cluster-design/004-cluster-design.md](url)， You mentioned http client 3 times.
But In elasticsearch concept, there is only master client, data client, ingest client, coordinate client, there is no http client.
So I want to know the meaning of http client?
I think the http client is coordinate client，I want to konw the real meaning
Thanks！

**Comment by fdv** [comment]
This is ingest, they changed the name long after I started using it. I'll change this
